#!/usr/bin/env python3
"""
build_tier2_index.py — section-level index for Tier 2 raw sources.

Scans raw_processed/** (READ-ONLY — Guardrail #1: raw is never modified) and emits
wiki/tier2-sections.md mapping each heading to source-file:line-range. When a query
falls through Tier 1, the agent greps this file for the topic, gets a precise
line-range, and reads only that slice instead of a 10–18k-line document.

Grep this file; never full-read it. Stdlib only; re-run when raw_processed changes.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "raw_processed"
OUT = ROOT / "wiki" / "tier2-sections.md"

HEADING_RE = re.compile(r"^(#{1,3})\s+(.+?)\s*$")
BOLD_RE = re.compile(r"^\*\*([^*]+)\*\*\s*$")   # some sources use **bold** lines as headings
TEXT_CAP = 100
BLOCK = 100                                     # line-block size for flat (heading-less) files


def block_anchors(lines):
    """Fallback for files with no '#' or bold headings: an anchor every BLOCK lines,
    labelled with the first substantive line in the block so it stays greppable."""
    anchors = []
    for start in range(0, len(lines), BLOCK):
        preview = ""
        for ln in lines[start:start + BLOCK]:
            s = ln.strip()
            if len(s) >= 12 and not s.startswith(("---", "|", "```", "!", "#")):
                preview = s[:TEXT_CAP]
                break
        anchors.append((start + 1, 1, f"[block] {preview or 'lines ' + str(start + 1)}"))
    return anchors


def main():
    files = sorted(RAW.rglob("*.md"))
    out = [
        "# Tier 2 Section Index",
        "",
        "> GENERATED by `scripts/build_tier2_index.py` — do not hand-edit. "
        "GREP this for a topic to get `source-file:line-range`, then Read only that slice. "
        "Raw sources are immutable (Guardrail #1).",
        "",
    ]
    total_sections = 0

    for f in files:
        rel = f.relative_to(ROOT).as_posix()
        lines = f.read_text(encoding="utf-8", errors="ignore").splitlines()
        heads = []  # (lineno_1based, level, text)
        for i, line in enumerate(lines, start=1):
            m = HEADING_RE.match(line)
            if m:
                heads.append((i, len(m.group(1)), m.group(2)[:TEXT_CAP]))
        if not heads:  # no '#' headings — try **bold** lines used as headings
            for i, line in enumerate(lines, start=1):
                b = BOLD_RE.match(line)
                if b:
                    heads.append((i, 2, b.group(1).strip()[:TEXT_CAP]))
        if not heads:  # still flat — fixed line-block anchors with a content preview
            heads = block_anchors(lines)
        if not heads:
            continue
        out.append(f"## {rel}  ({len(lines)} lines)")
        for idx, (lineno, level, text) in enumerate(heads):
            end = heads[idx + 1][0] - 1 if idx + 1 < len(heads) else len(lines)
            indent = "  " * (level - 1)
            out.append(f"{indent}{text} | {rel}:{lineno}-{end}")
            total_sections += 1
        out.append("")

    out.insert(3, f"> {len(files)} sources · {total_sections} sections")
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(files)} sources, {total_sections} sections")


if __name__ == "__main__":
    main()
